project:
  type: book
  output-dir: docs


book:
  title: "Differential Geometry"
  subtitle: "Lecture Notes, T1 2023"
  author: 
    - name: "Silvio Fanzon"
      affiliations: "University of Hull"
      email: "S.Fanzon@hull.ac.uk"
      url: "https://www.silviofanzon.com"
  date: "1/9/2023"
  downloads: pdf
  favicon: images/favicon.png
  search:
    location: navbar
    type: overlay
  page-footer:
    center: 
      - text: "License"
        href: sections/license.qmd
      - text: "Contact" 
        href: https://www.silviofanzon.com/contact
  navbar:
    search: true
    pinned: false
    background: black
    foreground: "#E8E8E8"
  sidebar:
    search: false
  


  chapters:
    - index.qmd
    - sections/chap1.qmd
    - sections/chap2.qmd
    - sections/chap3.qmd
    - sections/chap4.qmd
    - sections/license.qmd
    - sections/references.qmd


bibliography: teaching.bib
csl: comptes-rendus-mathematique.csl


format:
  html:
    toc: true
    toc-title: On this page
    toc-location: right
    code-overflow: wrap
    execute:
      freeze: auto
    theme:
      light: [flatly, theme-custom.scss]
      dark: [darkly]
  pdf:
    documentclass: scrreprt
    fontsize: 13pt
    geometry:
      - top=25mm
      - left=15mm
      - right=15mm
      - bottom=15mm
      - heightrounded
    link-citations: true
    linkcolor: magenta
    urlcolor: magenta
    citecolor: magenta
    cite-method: biblatex
    biblatexoptions: maxbibnames=99, style=numeric, giveninits=true, url=true
    include-in-header:
      - text: |
          \usepackage{scrlayer-scrpage}
          \lohead{Differential Geometry}
          \cohead{}
          \rohead{\pagemark}
          \lofoot{}
          \cofoot{}
          \rofoot{}
          \setheadsepline{0.5pt}
          \addtokomafont{pageheadfoot}{\color{gray}\textnormal}
          \setkomafont{pagenumber}{} 
