::: {.content-hidden}
$$
{{< include sections/macros.tex >}}
$$
:::


# Welcome {.unnumbered}

These are the Lecture Notes of **Differential Geometry 600727** for T1 2023 at the University of Hull. We will study curves and surfaces in $\R^3$. I will follow these lecture notes during the course. If you have any question or find any typo, please email me at

<div style="text-align: center;">
**[S.Fanzon@hull.ac.uk](mailto: S.Fanzon@hull.ac.uk)**
</div>

Up to date informations about the course and homework will be published on the **`course webpage`**


<div style="text-align: center;">
**[silviofanzon.com/blog/2023/Differential-Geometry](https://www.silviofanzon.com/blog/2023/Differential-Geometry/)**
</div>


A **pdf** version of the notes is available to download on the top-right.




## References {.unnumbered}

The main textbook of the course is Pressley [@pressley]. Other useful references are the books by do Carmo [@do-carmo] and Bär [@bar]. I will assume some knowledge from Analysis and Linear Algebra. A good place to revise these topics are the books by Zorich [@zorich-1; @zorich-2]. 


## Visualization {.unnumbered} 

It is important to visualize the geometrical objects and concepts we are 
going to talk about in this course. I will show basic Python code to plot curves and surfaces. This part of the course is **`not required`** for the final examination. If you want to have fun plotting with Pyhton, I recommend installation through [Anaconda](https://www.anaconda.com) or [Miniconda](https://docs.conda.io/en/latest/miniconda.html). The actual coding can then be done through [Jupyter Notebook](https://jupyter.org). Good references for scientific Python programming are [@johansson;@KSB-Python].   
If you do not want to mess around with Python, do not despair. You can still visualize pretty much everything we will do in this course using the excellent online 3D grapher tool [CalcPlot3D](https://c3d.libretexts.org/CalcPlot3D/index.html). To understand how it works, please refer to the [help manual](https://c3d.libretexts.org/CalcPlot3D/CalcPlot3D-Help/front.html) or to the short [video introduction](https://c3d.libretexts.org/CalcPlot3D/CalcPlot3D-Help/section-1.html).


::: {.callout-important}
You are not expected to purchase any of the above books. These lecture notes will cover 100% of the topics you are expected to known in order to excel in the final exam.
:::