::: {.content-hidden}
$$
{{< include macros.tex >}}
$$
:::





# Surfaces


::: Definition

A set $\SSS \subset \R^3$ is a **surface** if for every point $\pp \in \SSS$ there exist open sets $U \subset \R^2$, $V \subset \R^3$ such that

- $\pp \in V$,
- $U$ is diffeomorphic to $V \cap \SSS$.

Further:

- A diffeomorphism of $U$ into $V \cap \SSS$, denoted by
$$
\sss \colon U \to  V \cap \SSS \,
$$
is called a **surface chart**. 
- For each $i \in I$ suppose to have a surface chart
$$
\sss_i  \colon U_i \to V_i \cap \SSS \,.
$$
We say that the family $\{ \sss_i\}_{i \in I}$ is an **atlas** of $\SSS$ if 
$$
\bigcup_{i \in I} (V_i \cap \SSS ) = \SSS \,.
$$
:::
 
Note that a surface chart $\sss$ is a map from $\R^2$ into $\R^3$.
Points in $U$ will be denoted by the pair $(u,v)$, while points on $\SSS$ by $\pp$ and points in $\R^3$ by $\xx$.


::: Definition

Let $U \subset \R^2$ be open A surface chart 
$$
\sss = \sss(u,v)  \colon U \to \R^3
$$
is called **regular** if the partial derivatives
$$
\sss_u(u,v) = \frac{d\sss}{du}(u,v) \,, \quad
\sss_v(u,v) = \frac{d\sss}{dv}(u,v) 
$$
are linearly independent vectors of $\R^3$ for all $(u,v) \in U$.
:::




::: Definition

Let $U \subset \R^2$ be open. A surface chart 
$$
\sss \colon U \to \R^3
$$
is called a **conformal parametrization** if the first fundamental form satisfies
$$
E \, du^2 + F \, du \ dv + G \, dv^2 = \lambda(u,v)  ( du^2 +  dv^2)
$$
for some smooth function $\lambda  \colon U \to \R$.


:::




::: Definition

Let $\SSS$ be a surface and $\sss \colon U \to V \cap \SSS$  a surface chart. The principal unit normal to $\SSS$ is 
$$
\mathbf{N} = \frac{ \sss_u \times \sss_v }{ \norm{\sss_u \times \sss_v} } \,. 
$$
:::



Denote by 
$$
\sphere^2 = \{ \xx \in \R^3 \, \colon \, \norm{\xx} = 1 \} 
$$
the unit sphere in $\R^3$.

::: Definition

Let $\SSS$ be a surface and denote by $\mathbf{N}$ the principal unit normal. The **Gauss map** of $\SSS$ is the map $G \colon \SSS  \to \sphere^2$ defined by 
$$
G(\pp):= \NN(\pp) \,.
$$
The **Weingarten map** is the derivative of the Gauss map, denoted by $\WW \colon T_{\pp}\SSS  \to T_{G(\pp)} \sphere^2$.
:::


